name = "Schrute"
uuid = "24ea3d2b-16a5-4a86-8786-5f5ee87bc758"
authors = ["Brad Lindblad"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
DataFrames = "0.20.2"
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
